---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
- type: directory
  path: content/support
  label: Support
  create: all
  match: "*"
  templates:
  - taggable
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.49'

build:
  preview_command: hugo -D -F -E
  publish_command: hugo
  output_directory: public
  preview_env:
  - HUGO_ENV=staging
  publish_env:
  - HUGO_ENV=production
